### PR TITLE
Update cfgv pinning

### PR DESCRIPTION
**Pull request by xmnlab**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xmnlab** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
cfgv <1.4 raises:

```
12:19 $ pre-commit --version
Traceback (most recent call last):
  File "/mnt/sda1/storage/miniconda/envs/ibis/bin/pre-commit", line 7, in <module>
    from pre_commit.main import main
  File "/mnt/sda1/storage/miniconda/envs/ibis/lib/python3.6/site-packages/pre_commit/main.py", line 12, in <module>
    from pre_commit.commands.autoupdate import autoupdate
  File "/mnt/sda1/storage/miniconda/envs/ibis/lib/python3.6/site-packages/pre_commit/commands/autoupdate.py", line 14, in <module>
    from pre_commit.clientlib import CONFIG_SCHEMA
  File "/mnt/sda1/storage/miniconda/envs/ibis/lib/python3.6/site-packages/pre_commit/clientlib.py", line 180, in <module>
    for hook_id, values in _meta
  File "/mnt/sda1/storage/miniconda/envs/ibis/lib/python3.6/site-packages/pre_commit/clientlib.py", line 181, in <listcomp>
    for key, value in values
AttributeError: module 'cfgv' has no attribute 'ConditionalOptional'
```

**Comment by xmnlab** [comment]
@conda-forge/pre_commit any thoughts about that?

**Comment by asottile** [comment]
yes, the deps don't match properly:

https://github.com/pre-commit/pre-commit/blob/b33f2c40d8de0cd2c55a9b637773172198962832/setup.cfg#L26-L37

**Comment by xmnlab** [comment]
it is done for a review.

**Review by asottile — APPROVED** [review]

**Comment by xmnlab** [comment]
thanks @asottile for the review!
could this be merged?

**Review by nicoddemus — APPROVED** [review]
Thanks @xmnlab!

**Comment by xmnlab** [comment]
thanks @nicoddemus !

**Pull request merged**
