### PR TITLE
Add dependency to importlib_resources for py<37

### LINKED ISSUE #16: Missing dependency on `importlib-resources`
(I don't use conda, just reporting a downstream issue)

For python<3.7, `importlib-resources` is necessary: https://github.com/pre-commit/pre-commit/issues/853

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #16

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
@ocefpaf, is it normal that this is not generating a `py37` package? 🤔

**Comment by ocefpaf** [comment]
> @ocefpaf, is it normal that this is not generating a `py37` package?

Looks like the migration PR kicked in #18 
Let me know if you don't see a PY37 package after that one.

**Comment by nicoddemus** [comment]
Cool, will do. 👍 

Out of curiosity, what needs to be done to trigger py37 builds? Is there an explanation somewhere that I can read about?

**Comment by ocefpaf** [comment]
> Out of curiosity, what needs to be done to trigger py37 builds? Is there an explanation somewhere that I can read about?

No docs. Sorry :flushed: 

As soon as the migration is over it will be automatic but if you want to force it you can add [this line](https://github.com/conda-forge/pre_commit-feedstock/blob/master/conda-forge.yml#L4) to your `conda-forge.yml` and re-render.

**Comment by nicoddemus** [comment]
I see, thanks! That's the little nugget of information I was looking for. 👍

**Pull request merged**
